name = "spinogambinojogos-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinojogos.com.pt"
HMAC_KEY = "8b31a0bf25a4fe0eb10ce9c407b917747ad83abd0a2b70dd65def1993621b523"
COOKIE_NAME = "8q9"
PLAY_PATH = "discover"
BUTTON_ID = "pe5f1174e242592846596bb74a8e1e15e"
GATE_SALT = "74df30804e7ee05c"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "u8ct"
CTA_SELECTOR = ".play-button"
